//! Secure Handshake Protocol
//!
//! Implements the ECDH key exchange handshake for establishing encrypted sessions.
//! Each handshake carries a unique `handshake_id` (UUIDv4) so that two concurrent
//! handshakes to the same peer device never share a key in `pending_keypairs` and
//! can never overwrite each other's ephemeral keypair.

#![allow(dead_code)]

use crate::crypto::session::{Keypair, Session};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use uuid::Uuid;

/// Handshake manager maintains keypairs and sessions for active connections
pub struct HandshakeManager {
    /// Ephemeral keypairs for ongoing handshakes (cleared after session established)
    pending_keypairs: Arc<Mutex<HashMap<String, Keypair>>>,
    /// Established sessions keyed by peer device ID
    sessions: Arc<Mutex<HashMap<String, Session>>>,
}

/// Secure HELLO message with public key.
///
/// `handshake_id` is a per-connection UUIDv4 generated by the initiator.
/// The responder echoes it back in `HelloResponse` so the initiator can look
/// up the correct ephemeral keypair even when multiple handshakes to the same
/// peer are in flight at the same time.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HelloSecure {
    pub device_id: String,
    pub display_name: String,
    pub platform: String,
    pub app_version: String,
    #[serde(with = "base64_serde")]
    pub public_key: [u8; 32],
    /// Unique per-handshake identifier (UUIDv4). Echoed back by the server in
    /// `HelloResponse` so the client can retrieve the correct keypair.
    pub handshake_id: String,
}

/// HELLO_RESPONSE with our public key
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HelloResponse {
    pub device_id: String,
    pub display_name: String,
    pub platform: String,
    pub app_version: String,
    #[serde(with = "base64_serde")]
    pub public_key: [u8; 32],
    pub accepted: bool,
    /// Echoed from the initiator's `HelloSecure.handshake_id` so the client
    /// can unambiguously match this response to its pending keypair.
    pub handshake_id: String,
}

/// Handshake state
#[derive(Debug, Clone, PartialEq)]
pub enum HandshakeState {
    /// No handshake initiated
    None,
    /// Waiting for HELLO_RESPONSE
    WaitingForResponse,
    /// Handshake complete, session established
    Established,
    /// Handshake failed
    Failed(String),
}

impl HandshakeManager {
    /// Create a new handshake manager
    pub fn new() -> Self {
        Self {
            pending_keypairs: Arc::new(Mutex::new(HashMap::new())),
            sessions: Arc::new(Mutex::new(HashMap::new())),
        }
    }

    /// Initiate a handshake with a peer (as client).
    ///
    /// Generates a fresh ephemeral X25519 keypair and a unique `handshake_id`.
    /// The keypair is stored under `handshake_id` (not `peer_device_id`) so
    /// that concurrent handshakes to the same device never overwrite each other.
    pub fn initiate_handshake(
        &self,
        our_device_id: &str,
        display_name: &str,
        platform: &str,
        app_version: &str,
        _peer_device_id: &str,
    ) -> Result<HelloSecure, String> {
        // Generate ephemeral keypair and a unique per-handshake ID.
        let keypair = Keypair::generate();
        let public_key = keypair.public_bytes();
        let handshake_id = Uuid::new_v4().to_string();

        // Key by handshake_id so concurrent handshakes to the same peer are
        // completely independent.
        self.pending_keypairs
            .lock()
            .unwrap()
            .insert(handshake_id.clone(), keypair);

        Ok(HelloSecure {
            device_id: our_device_id.to_string(),
            display_name: display_name.to_string(),
            platform: platform.to_string(),
            app_version: app_version.to_string(),
            public_key,
            handshake_id,
        })
    }

    /// Handle incoming HELLO_SECURE (as server).
    ///
    /// The server stores its keypair under the initiator's `handshake_id` and
    /// echoes that same id back in `HelloResponse` so both sides can look up
    /// their keypairs unambiguously.
    pub fn handle_hello_secure(
        &self,
        hello: HelloSecure,
        our_device_id: &str,
        display_name: &str,
        platform: &str,
        app_version: &str,
    ) -> Result<HelloResponse, String> {
        // Generate ephemeral keypair.
        let keypair = Keypair::generate();
        let public_key = keypair.public_bytes();

        // Store under the initiator's handshake_id so concurrent handshakes
        // from the same device never collide.
        self.pending_keypairs
            .lock()
            .unwrap()
            .insert(hello.handshake_id.clone(), keypair);

        Ok(HelloResponse {
            device_id: our_device_id.to_string(),
            display_name: display_name.to_string(),
            platform: platform.to_string(),
            app_version: app_version.to_string(),
            public_key,
            accepted: true,
            // Echo back so the initiator can match this response to its keypair.
            handshake_id: hello.handshake_id,
        })
    }

    /// Complete handshake after receiving HELLO_RESPONSE (as client).
    ///
    /// Looks up the keypair by `response.handshake_id` (not `device_id`) so
    /// that two concurrent handshakes to the same peer retrieve the correct
    /// keypair and derive independent, matching session keys.
    pub fn complete_handshake(&self, response: HelloResponse) -> Result<Session, String> {
        // Retrieve our keypair using the unique handshake ID, not device_id.
        let mut pending = self.pending_keypairs.lock().unwrap();
        let keypair = pending
            .remove(&response.handshake_id)
            .ok_or("No pending handshake matching this handshake_id")?;

        // Perform ECDH and derive session.
        let session = Session::from_ecdh(keypair.secret, &response.public_key)?;

        // Store session under the peer's device_id for later retrieval.
        self.sessions
            .lock()
            .unwrap()
            .insert(response.device_id.clone(), session.clone());

        Ok(session)
    }

    /// Finalize handshake after sending HELLO_RESPONSE (as server).
    ///
    /// Looks up the keypair by `handshake_id` (not `peer_device_id`) for the
    /// same reason as `complete_handshake`: concurrent incoming connections
    /// from the same client must never share keypair storage.
    pub fn finalize_handshake(
        &self,
        peer_device_id: &str,
        peer_public_key: &[u8; 32],
        handshake_id: &str,
    ) -> Result<Session, String> {
        // Retrieve our keypair using the unique handshake ID.
        let mut pending = self.pending_keypairs.lock().unwrap();
        let keypair = pending
            .remove(handshake_id)
            .ok_or("No pending handshake matching this handshake_id")?;

        // Perform ECDH and derive session.
        let session = Session::from_ecdh(keypair.secret, peer_public_key)?;

        // Store session under peer_device_id for later lookup.
        self.sessions
            .lock()
            .unwrap()
            .insert(peer_device_id.to_string(), session.clone());

        Ok(session)
    }

    /// Get an established session for a peer
    pub fn get_session(&self, peer_device_id: &str) -> Option<Session> {
        self.sessions.lock().unwrap().get(peer_device_id).cloned()
    }

    /// Check if a session exists for a peer
    pub fn has_session(&self, peer_device_id: &str) -> bool {
        self.sessions.lock().unwrap().contains_key(peer_device_id)
    }

    /// Remove a session (on disconnect)
    pub fn remove_session(&self, peer_device_id: &str) {
        self.sessions.lock().unwrap().remove(peer_device_id);
        self.pending_keypairs.lock().unwrap().remove(peer_device_id);
    }

    /// Clear all sessions and pending handshakes
    pub fn clear_all(&self) {
        self.sessions.lock().unwrap().clear();
        self.pending_keypairs.lock().unwrap().clear();
    }

    /// Get count of active sessions
    pub fn session_count(&self) -> usize {
        self.sessions.lock().unwrap().len()
    }

    /// Get count of pending handshakes
    pub fn pending_count(&self) -> usize {
        self.pending_keypairs.lock().unwrap().len()
    }
}

impl Default for HandshakeManager {
    fn default() -> Self {
        Self::new()
    }
}

// Ensure HandshakeManager is Send + Sync
unsafe impl Send for HandshakeManager {}
unsafe impl Sync for HandshakeManager {}

/// Helper module for base64 serialization of byte arrays
mod base64_serde {
    use base64::{engine::general_purpose::STANDARD, Engine};
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S>(bytes: &[u8; 32], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let encoded = STANDARD.encode(bytes);
        serializer.serialize_str(&encoded)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<[u8; 32], D::Error>
    where
        D: Deserializer<'de>,
    {
        let encoded = String::deserialize(deserializer)?;
        let decoded = STANDARD
            .decode(&encoded)
            .map_err(serde::de::Error::custom)?;

        if decoded.len() != 32 {
            return Err(serde::de::Error::custom("Invalid key length"));
        }

        let mut bytes = [0u8; 32];
        bytes.copy_from_slice(&decoded);
        Ok(bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_handshake_manager_creation() {
        let manager = HandshakeManager::new();
        assert_eq!(manager.session_count(), 0);
        assert_eq!(manager.pending_count(), 0);
    }

    #[test]
    fn test_full_handshake_flow() {
        // Simulate Alice and Bob
        let alice_manager = HandshakeManager::new();
        let bob_manager = HandshakeManager::new();

        let alice_id = "alice-uuid";
        let bob_id = "bob-uuid";

        // Alice initiates handshake
        let hello = alice_manager
            .initiate_handshake(alice_id, "Alice", "macos", "0.1.0", bob_id)
            .unwrap();

        assert_eq!(hello.device_id, alice_id);
        assert!(!hello.handshake_id.is_empty());
        assert_eq!(alice_manager.pending_count(), 1);

        // Bob receives HELLO_SECURE and responds
        let response = bob_manager
            .handle_hello_secure(hello.clone(), bob_id, "Bob", "linux", "0.1.0")
            .unwrap();

        assert_eq!(response.device_id, bob_id);
        assert!(response.accepted);
        assert_eq!(response.handshake_id, hello.handshake_id);
        assert_eq!(bob_manager.pending_count(), 1);

        // Bob finalizes his side using the handshake_id
        let _bob_session = bob_manager
            .finalize_handshake(alice_id, &hello.public_key, &hello.handshake_id)
            .unwrap();

        assert_eq!(bob_manager.session_count(), 1);
        assert_eq!(bob_manager.pending_count(), 0);
        assert!(bob_manager.has_session(alice_id));

        // Alice receives HELLO_RESPONSE and completes handshake
        let _alice_session = alice_manager.complete_handshake(response).unwrap();

        assert_eq!(alice_manager.session_count(), 1);
        assert_eq!(alice_manager.pending_count(), 0);
        assert!(alice_manager.has_session(bob_id));

        // Both should have valid sessions
        assert!(alice_manager.get_session(bob_id).is_some());
        assert!(bob_manager.get_session(alice_id).is_some());
    }

    #[test]
    fn test_concurrent_handshakes_to_same_peer() {
        // Two simultaneous handshakes to the same peer must not corrupt each
        // other's keypairs.
        let alice_manager = HandshakeManager::new();
        let bob_manager = HandshakeManager::new();

        let alice_id = "alice-uuid";
        let bob_id = "bob-uuid";

        // Alice opens two connections to Bob concurrently.
        let hello1 = alice_manager
            .initiate_handshake(alice_id, "Alice", "macos", "0.1.0", bob_id)
            .unwrap();
        let hello2 = alice_manager
            .initiate_handshake(alice_id, "Alice", "macos", "0.1.0", bob_id)
            .unwrap();

        // The two handshake IDs must be distinct.
        assert_ne!(hello1.handshake_id, hello2.handshake_id);
        assert_eq!(alice_manager.pending_count(), 2);

        // Bob handles both concurrently.
        let resp1 = bob_manager
            .handle_hello_secure(hello1.clone(), bob_id, "Bob", "linux", "0.1.0")
            .unwrap();
        let resp2 = bob_manager
            .handle_hello_secure(hello2.clone(), bob_id, "Bob", "linux", "0.1.0")
            .unwrap();

        assert_ne!(resp1.handshake_id, resp2.handshake_id);

        let _bob_session1 = bob_manager
            .finalize_handshake(alice_id, &hello1.public_key, &hello1.handshake_id)
            .unwrap();
        let _bob_session2 = bob_manager
            .finalize_handshake(alice_id, &hello2.public_key, &hello2.handshake_id)
            .unwrap();

        // Alice completes both – each must resolve to the correct keypair.
        let alice_session1 = alice_manager.complete_handshake(resp1).unwrap();
        let alice_session2 = alice_manager.complete_handshake(resp2).unwrap();

        assert_eq!(alice_manager.pending_count(), 0);

        // Sanity: sessions derived from different ECDH exchanges should differ.
        // (They encrypt different things; we just verify both succeed.)
        let _ = alice_session1;
        let _ = alice_session2;
    }

    #[test]
    fn test_session_removal() {
        let manager = HandshakeManager::new();
        let peer_id = "peer-uuid";

        // Initiate a handshake – this stores the keypair under a unique
        // handshake_id, NOT under peer_id.
        let hello = manager
            .initiate_handshake("me", "Me", "linux", "0.1.0", peer_id)
            .unwrap();

        assert_eq!(manager.pending_count(), 1);

        // remove_session operates on *established* sessions (keyed by
        // peer_device_id) and pending_keypairs keyed by peer_device_id
        // (legacy). Pending keypairs are now keyed by handshake_id, so
        // remove_session does not clear them – clear_all() does that.
        manager.remove_session(peer_id);

        // pending_keypairs is still 1 (keyed by hello.handshake_id, not peer_id)
        assert_eq!(manager.pending_count(), 1);
        assert_eq!(manager.session_count(), 0);

        // Explicitly clear everything to verify clear_all still works.
        manager.clear_all();
        assert_eq!(manager.pending_count(), 0);

        // Use handshake_id to demonstrate the keypair was there.
        let _ = hello.handshake_id;
    }

    #[test]
    fn test_clear_all() {
        let manager = HandshakeManager::new();

        // Create multiple pending handshakes
        let _ = manager
            .initiate_handshake("me", "Me", "linux", "0.1.0", "peer1")
            .unwrap();
        let _ = manager
            .initiate_handshake("me", "Me", "linux", "0.1.0", "peer2")
            .unwrap();

        assert_eq!(manager.pending_count(), 2);

        manager.clear_all();

        assert_eq!(manager.pending_count(), 0);
        assert_eq!(manager.session_count(), 0);
    }

    #[test]
    fn test_hello_secure_serialization() {
        let hello = HelloSecure {
            device_id: "test-uuid".to_string(),
            display_name: "Test Device".to_string(),
            platform: "linux".to_string(),
            app_version: "0.1.0".to_string(),
            public_key: [0x42; 32],
            handshake_id: Uuid::new_v4().to_string(),
        };

        let json = serde_json::to_string(&hello).unwrap();
        let deserialized: HelloSecure = serde_json::from_str(&json).unwrap();

        assert_eq!(hello.device_id, deserialized.device_id);
        assert_eq!(hello.public_key, deserialized.public_key);
        assert_eq!(hello.handshake_id, deserialized.handshake_id);
    }
}
