//! TLS Transport-Layer Encryption
//!
//! Provides TLS 1.3 transport encryption for all TCP connections using
//! self-signed certificates with a Trust-On-First-Use (TOFU) model
//! suitable for LAN peer-to-peer communication.
//!
//! ## Design
//!
//! - Each device generates a self-signed certificate on first run
//! - Certificates are persisted to the app data directory
//! - The server presents its self-signed certificate
//! - The client accepts any certificate (TOFU — no CA infrastructure)
//! - Application-layer crypto (X25519 + AES-256-GCM) remains as defense-in-depth
//!
//! ## Certificate Lifecycle
//!
//! - Generated once at first launch via `rcgen`
//! - Stored as PEM files in the app data directory
//! - Reused across restarts for consistent identity
//! - Can be regenerated by deleting the PEM files

use base64::Engine;
use rcgen::{CertificateParams, KeyPair};
use rustls::pki_types::{CertificateDer, PrivateKeyDer, PrivatePkcs8KeyDer};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio_rustls::{TlsAcceptor, TlsConnector};

/// Filenames for persisted certificate and key
const CERT_FILENAME: &str = "hyper-connect-cert.pem";
const KEY_FILENAME: &str = "hyper-connect-key.pem";

/// TLS configuration holder for the application.
///
/// Created once at startup and shared across all server/client connections.
#[derive(Clone)]
pub struct TlsConfig {
    /// TLS acceptor for the server side (wraps incoming TCP streams)
    pub acceptor: TlsAcceptor,
    /// TLS connector for the client side (wraps outgoing TCP streams)
    pub connector: TlsConnector,
}

impl TlsConfig {
    /// Initialize TLS configuration.
    ///
    /// Loads or generates a self-signed certificate, then builds both
    /// a `TlsAcceptor` (server) and `TlsConnector` (client).
    ///
    /// # Arguments
    /// * `data_dir` - Directory to store/load certificate files
    pub fn new(data_dir: &Path) -> Result<Self, String> {
        let cert_path = data_dir.join(CERT_FILENAME);
        let key_path = data_dir.join(KEY_FILENAME);

        let (cert_der, key_der) = if cert_path.exists() && key_path.exists() {
            println!("TLS: Loading existing certificate from {:?}", cert_path);
            load_cert_and_key(&cert_path, &key_path)?
        } else {
            println!("TLS: Generating new self-signed certificate");
            let (cert, key) = generate_self_signed_cert()?;
            save_cert_and_key(&cert, &key, &cert_path, &key_path)?;
            (cert, key)
        };

        // Build server config
        let server_config = rustls::ServerConfig::builder()
            .with_no_client_auth()
            .with_single_cert(vec![cert_der], key_der)
            .map_err(|e| format!("Failed to build TLS server config: {}", e))?;

        let acceptor = TlsAcceptor::from(Arc::new(server_config));

        // Build client config that accepts any server certificate (TOFU model)
        let client_config = rustls::ClientConfig::builder()
            .dangerous()
            .with_custom_certificate_verifier(Arc::new(AcceptAnyCertVerifier))
            .with_no_client_auth();

        let connector = TlsConnector::from(Arc::new(client_config));

        println!("TLS: Configuration initialized successfully");

        Ok(Self {
            acceptor,
            connector,
        })
    }
}

/// Generate a new self-signed certificate and private key.
fn generate_self_signed_cert() -> Result<(CertificateDer<'static>, PrivateKeyDer<'static>), String>
{
    let mut params = CertificateParams::new(vec!["hyper-connect.local".to_string()])
        .map_err(|e| format!("Failed to create cert params: {}", e))?;

    params.distinguished_name = rcgen::DistinguishedName::new();
    params
        .distinguished_name
        .push(rcgen::DnType::CommonName, "Hyper-Connect Device");
    params
        .distinguished_name
        .push(rcgen::DnType::OrganizationName, "Hyper-Connect");

    // Add Subject Alternative Names for LAN use
    params.subject_alt_names = vec![
        rcgen::SanType::DnsName(
            "hyper-connect.local"
                .try_into()
                .map_err(|e| format!("Invalid DNS name: {}", e))?,
        ),
        rcgen::SanType::DnsName(
            "localhost"
                .try_into()
                .map_err(|e| format!("Invalid DNS name: {}", e))?,
        ),
    ];

    let key_pair =
        KeyPair::generate().map_err(|e| format!("Failed to generate key pair: {}", e))?;

    let cert = params
        .self_signed(&key_pair)
        .map_err(|e| format!("Failed to generate self-signed cert: {}", e))?;

    let cert_der = CertificateDer::from(cert.der().to_vec());
    let key_der = PrivateKeyDer::Pkcs8(PrivatePkcs8KeyDer::from(key_pair.serialize_der()));

    Ok((cert_der, key_der))
}

/// Save certificate and key as PEM files.
fn save_cert_and_key(
    cert: &CertificateDer<'_>,
    key: &PrivateKeyDer<'_>,
    cert_path: &PathBuf,
    key_path: &PathBuf,
) -> Result<(), String> {
    // Ensure parent directory exists
    if let Some(parent) = cert_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create cert directory: {}", e))?;
    }

    // Write certificate PEM
    let cert_pem = encode_pem("CERTIFICATE", cert.as_ref());
    std::fs::write(cert_path, &cert_pem)
        .map_err(|e| format!("Failed to write certificate: {}", e))?;

    // Write key PEM
    let key_bytes = match key {
        PrivateKeyDer::Pkcs8(k) => k.secret_pkcs8_der().to_vec(),
        _ => return Err("Unexpected key format".to_string()),
    };
    let key_pem = encode_pem("PRIVATE KEY", &key_bytes);
    std::fs::write(key_path, &key_pem)
        .map_err(|e| format!("Failed to write private key: {}", e))?;

    // Restrict key file permissions on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600);
        std::fs::set_permissions(key_path, perms)
            .map_err(|e| format!("Failed to set key permissions: {}", e))?;
    }

    println!("TLS: Certificate saved to {:?}", cert_path);
    Ok(())
}

/// Load certificate and key from PEM files.
fn load_cert_and_key(
    cert_path: &Path,
    key_path: &Path,
) -> Result<(CertificateDer<'static>, PrivateKeyDer<'static>), String> {
    // Read and parse certificate
    let cert_pem =
        std::fs::read(cert_path).map_err(|e| format!("Failed to read certificate: {}", e))?;
    let mut cert_reader = std::io::BufReader::new(cert_pem.as_slice());
    let certs: Vec<CertificateDer<'static>> = rustls_pemfile::certs(&mut cert_reader)
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| format!("Failed to parse certificate PEM: {}", e))?;
    let cert = certs
        .into_iter()
        .next()
        .ok_or("No certificate found in PEM file")?;

    // Read and parse private key
    let key_pem =
        std::fs::read(key_path).map_err(|e| format!("Failed to read private key: {}", e))?;
    let mut key_reader = std::io::BufReader::new(key_pem.as_slice());
    let key = rustls_pemfile::private_key(&mut key_reader)
        .map_err(|e| format!("Failed to parse key PEM: {}", e))?
        .ok_or("No private key found in PEM file")?;

    Ok((cert, key))
}

/// Encode binary data as a PEM string with the given label.
fn encode_pem(label: &str, data: &[u8]) -> String {
    let b64 = base64::engine::general_purpose::STANDARD.encode(data);
    // PEM wraps base64 at 64 characters per line
    let lines: Vec<&str> = b64
        .as_bytes()
        .chunks(64)
        .map(|chunk| std::str::from_utf8(chunk).unwrap())
        .collect();
    format!(
        "-----BEGIN {}-----\n{}\n-----END {}-----\n",
        label,
        lines.join("\n"),
        label
    )
}

/// Custom certificate verifier that accepts any server certificate.
///
/// This implements the TOFU (Trust On First Use) model for LAN peers.
/// Since there is no CA infrastructure for local network devices, we
/// accept any certificate presented by the peer. The application-layer
/// ECDH handshake (X25519 + AES-256-GCM) provides the actual
/// authenticated key exchange.
#[derive(Debug)]
struct AcceptAnyCertVerifier;

impl rustls::client::danger::ServerCertVerifier for AcceptAnyCertVerifier {
    fn verify_server_cert(
        &self,
        _end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &rustls::pki_types::ServerName<'_>,
        _ocsp_response: &[u8],
        _now: rustls::pki_types::UnixTime,
    ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
        // Accept any certificate — authentication is handled at the
        // application layer via ECDH handshake.
        Ok(rustls::client::danger::ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        Ok(rustls::client::danger::HandshakeSignatureValid::assertion())
    }

    fn verify_tls13_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        Ok(rustls::client::danger::HandshakeSignatureValid::assertion())
    }

    fn supported_verify_schemes(&self) -> Vec<rustls::SignatureScheme> {
        // Support all common signature schemes
        vec![
            rustls::SignatureScheme::ECDSA_NISTP256_SHA256,
            rustls::SignatureScheme::ECDSA_NISTP384_SHA384,
            rustls::SignatureScheme::ED25519,
            rustls::SignatureScheme::RSA_PSS_SHA256,
            rustls::SignatureScheme::RSA_PSS_SHA384,
            rustls::SignatureScheme::RSA_PSS_SHA512,
            rustls::SignatureScheme::RSA_PKCS1_SHA256,
            rustls::SignatureScheme::RSA_PKCS1_SHA384,
            rustls::SignatureScheme::RSA_PKCS1_SHA512,
        ]
    }
}
